apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-sebk
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mtuk-tenant/rhtap-demo-app/hacbs-test-project-sebk@sha256:dbf5104de61650c94e77ccd044f986b8f16ee7d15996a90aa9bbb0d45f5c12d0
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
