apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-sebk
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mtuk-tenant/rhtap-demo-app/hacbs-test-project-sebk@sha256:c359719b34b7c1435c13d8b590ebe68bcfea8fdf000ad26d86efa882e3138afe
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
